name: amap_core_fluttify
description: An `Amap` Core Component, Powered By `Fluttify` Engine, A Dart Bindings Generator For Native SDK.
version: 0.14.0
author: yohom <yohombao@qq.com>
homepage: https://github.com/fluttify-project/amap_core_fluttify

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

  core_location_fluttify:
    git:
      url: git://github.com/zileyuan/core_location_fluttify.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: me.yohom.amap_core_fluttify
        pluginClass: AmapCoreFluttifyPlugin
      ios:
        pluginClass: AmapCoreFluttifyPlugin